//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.Serv_Admin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMUsuario", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._Usuario")]
    [System.SerializableAttribute()]
    public partial class VMUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaDeRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaDeVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario_sistemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_materno {
            get {
                return this.Apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_maternoField, value) != true)) {
                    this.Apellido_maternoField = value;
                    this.RaisePropertyChanged("Apellido_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_paterno {
            get {
                return this.Apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_paternoField, value) != true)) {
                    this.Apellido_paternoField = value;
                    this.RaisePropertyChanged("Apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaDeRegistro {
            get {
                return this.FechaDeRegistroField;
            }
            set {
                if ((this.FechaDeRegistroField.Equals(value) != true)) {
                    this.FechaDeRegistroField = value;
                    this.RaisePropertyChanged("FechaDeRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaDeVencimiento {
            get {
                return this.FechaDeVencimientoField;
            }
            set {
                if ((this.FechaDeVencimientoField.Equals(value) != true)) {
                    this.FechaDeVencimientoField = value;
                    this.RaisePropertyChanged("FechaDeVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstatus {
            get {
                return this.IdEstatusField;
            }
            set {
                if ((this.IdEstatusField.Equals(value) != true)) {
                    this.IdEstatusField = value;
                    this.RaisePropertyChanged("IdEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_sistema {
            get {
                return this.Usuario_sistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario_sistemaField, value) != true)) {
                    this.Usuario_sistemaField = value;
                    this.RaisePropertyChanged("Usuario_sistema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
    [System.SerializableAttribute()]
    public partial class ExceptionService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionField, value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMRol", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._Rol")]
    [System.SerializableAttribute()]
    public partial class VMRol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMItemModulo", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._ItemModulo")]
    [System.SerializableAttribute()]
    public partial class VMItemModulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdItemModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdItemPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlIconoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlIconoModuloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItemModulo {
            get {
                return this.IdItemModuloField;
            }
            set {
                if ((this.IdItemModuloField.Equals(value) != true)) {
                    this.IdItemModuloField = value;
                    this.RaisePropertyChanged("IdItemModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItemPadre {
            get {
                return this.IdItemPadreField;
            }
            set {
                if ((this.IdItemPadreField.Equals(value) != true)) {
                    this.IdItemPadreField = value;
                    this.RaisePropertyChanged("IdItemPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo {
            get {
                return this.IdModuloField;
            }
            set {
                if ((this.IdModuloField.Equals(value) != true)) {
                    this.IdModuloField = value;
                    this.RaisePropertyChanged("IdModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSistema {
            get {
                return this.IdSistemaField;
            }
            set {
                if ((this.IdSistemaField.Equals(value) != true)) {
                    this.IdSistemaField = value;
                    this.RaisePropertyChanged("IdSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulo {
            get {
                return this.ModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloField, value) != true)) {
                    this.ModuloField = value;
                    this.RaisePropertyChanged("Modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlIcono {
            get {
                return this.UrlIconoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlIconoField, value) != true)) {
                    this.UrlIconoField = value;
                    this.RaisePropertyChanged("UrlIcono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlIconoModulo {
            get {
                return this.UrlIconoModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlIconoModuloField, value) != true)) {
                    this.UrlIconoModuloField = value;
                    this.RaisePropertyChanged("UrlIconoModulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMSistema", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._Sistema")]
    [System.SerializableAttribute()]
    public partial class VMSistema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmbebidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlHomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Embebido {
            get {
                return this.EmbebidoField;
            }
            set {
                if ((this.EmbebidoField.Equals(value) != true)) {
                    this.EmbebidoField = value;
                    this.RaisePropertyChanged("Embebido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSistema {
            get {
                return this.IdSistemaField;
            }
            set {
                if ((this.IdSistemaField.Equals(value) != true)) {
                    this.IdSistemaField = value;
                    this.RaisePropertyChanged("IdSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSistema {
            get {
                return this.NombreSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSistemaField, value) != true)) {
                    this.NombreSistemaField = value;
                    this.RaisePropertyChanged("NombreSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlHome {
            get {
                return this.UrlHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlHomeField, value) != true)) {
                    this.UrlHomeField = value;
                    this.RaisePropertyChanged("UrlHome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMModulo", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._Modulo")]
    [System.SerializableAttribute()]
    public partial class VMModulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DbConexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Entidades.Serv_Admin.VMItemModulo[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlIconoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbConexion {
            get {
                return this.DbConexionField;
            }
            set {
                if ((object.ReferenceEquals(this.DbConexionField, value) != true)) {
                    this.DbConexionField = value;
                    this.RaisePropertyChanged("DbConexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo {
            get {
                return this.IdModuloField;
            }
            set {
                if ((this.IdModuloField.Equals(value) != true)) {
                    this.IdModuloField = value;
                    this.RaisePropertyChanged("IdModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSistema {
            get {
                return this.IdSistemaField;
            }
            set {
                if ((this.IdSistemaField.Equals(value) != true)) {
                    this.IdSistemaField = value;
                    this.RaisePropertyChanged("IdSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Entidades.Serv_Admin.VMItemModulo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlDestino {
            get {
                return this.UrlDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlDestinoField, value) != true)) {
                    this.UrlDestinoField = value;
                    this.RaisePropertyChanged("UrlDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlIcono {
            get {
                return this.UrlIconoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlIconoField, value) != true)) {
                    this.UrlIconoField = value;
                    this.RaisePropertyChanged("UrlIcono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMPais", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._Pais")]
    [System.SerializableAttribute()]
    public partial class VMPais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMPermisoItem", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._PermisoItem")]
    [System.SerializableAttribute()]
    public partial class VMPermisoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdItemModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioPermisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WriteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Delete {
            get {
                return this.DeleteField;
            }
            set {
                if ((this.DeleteField.Equals(value) != true)) {
                    this.DeleteField = value;
                    this.RaisePropertyChanged("Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItemModulo {
            get {
                return this.IdItemModuloField;
            }
            set {
                if ((this.IdItemModuloField.Equals(value) != true)) {
                    this.IdItemModuloField = value;
                    this.RaisePropertyChanged("IdItemModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioPermisos {
            get {
                return this.IdUsuarioPermisosField;
            }
            set {
                if ((this.IdUsuarioPermisosField.Equals(value) != true)) {
                    this.IdUsuarioPermisosField = value;
                    this.RaisePropertyChanged("IdUsuarioPermisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRol {
            get {
                return this.NombreRolField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRolField, value) != true)) {
                    this.NombreRolField = value;
                    this.RaisePropertyChanged("NombreRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Write {
            get {
                return this.WriteField;
            }
            set {
                if ((this.WriteField.Equals(value) != true)) {
                    this.WriteField = value;
                    this.RaisePropertyChanged("Write");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VMToolItem", Namespace="http://schemas.datacontract.org/2004/07/ViewModel.Catalogo._ToolItem")]
    [System.SerializableAttribute()]
    public partial class VMToolItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdToolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioPermisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PermitirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTool {
            get {
                return this.IdToolField;
            }
            set {
                if ((this.IdToolField.Equals(value) != true)) {
                    this.IdToolField = value;
                    this.RaisePropertyChanged("IdTool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioPermisos {
            get {
                return this.IdUsuarioPermisosField;
            }
            set {
                if ((this.IdUsuarioPermisosField.Equals(value) != true)) {
                    this.IdUsuarioPermisosField = value;
                    this.RaisePropertyChanged("IdUsuarioPermisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Permitir {
            get {
                return this.PermitirField;
            }
            set {
                if ((this.PermitirField.Equals(value) != true)) {
                    this.PermitirField = value;
                    this.RaisePropertyChanged("Permitir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serv_Admin.IServiceGestion")]
    public interface IServiceGestion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarNuevoUsuario", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarNuevoUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/RegistrarNuevoUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMUsuario RegistrarNuevoUsuario(string nombre, string apellidoMaterno, string apellidoPaterno, string celular, string correo, string extension, int idEstatus, string password, string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarNuevoUsuario", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarNuevoUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario> RegistrarNuevoUsuarioAsync(string nombre, string apellidoMaterno, string apellidoPaterno, string celular, string correo, string extension, int idEstatus, string password, string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarUsuario", ReplyAction="http://tempuri.org/IServiceGestion/EditarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EditarUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EditarUsuario(Entidades.Serv_Admin.VMUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarUsuario", ReplyAction="http://tempuri.org/IServiceGestion/EditarUsuarioResponse")]
        System.Threading.Tasks.Task EditarUsuarioAsync(Entidades.Serv_Admin.VMUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoUsuarios", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoUsuariosExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMUsuario[] ObtenerCatalogoUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoUsuarios", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoUsuariosResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario[]> ObtenerCatalogoUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ResetPassUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ResetPassUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ResetPassUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void ResetPassUsuario(string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ResetPassUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ResetPassUsuarioResponse")]
        System.Threading.Tasks.Task ResetPassUsuarioAsync(string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerInfoUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMUsuario ObtenerInfoUsuario(string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario> ObtenerInfoUsuarioAsync(string usuario_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerRoles", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerRolesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerRolesExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMRol[] ObtenerRoles(int idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerRoles", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerRolesResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesAsync(int idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerRolesUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerRolesUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerRolesUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMRol[] ObtenerRolesUsuario(string usuario, System.Nullable<int> idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerRolesUsuario", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerRolesUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesUsuarioAsync(string usuario, System.Nullable<int> idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarNuevoRol", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarNuevoRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/RegistrarNuevoRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMRol RegistrarNuevoRol(string nombre, string descripcion, int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarNuevoRol", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarNuevoRolResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol> RegistrarNuevoRolAsync(string nombre, string descripcion, int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarRolUsuario", ReplyAction="http://tempuri.org/IServiceGestion/AsignarRolUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/AsignarRolUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void AsignarRolUsuario(int idRol, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarRolUsuario", ReplyAction="http://tempuri.org/IServiceGestion/AsignarRolUsuarioResponse")]
        System.Threading.Tasks.Task AsignarRolUsuarioAsync(int idRol, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EliminarRolUsuario", ReplyAction="http://tempuri.org/IServiceGestion/EliminarRolUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EliminarRolUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EliminarRolUsuario(int idRol, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EliminarRolUsuario", ReplyAction="http://tempuri.org/IServiceGestion/EliminarRolUsuarioResponse")]
        System.Threading.Tasks.Task EliminarRolUsuarioAsync(int idRol, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerItemsModulo", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerItemsModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerItemsModuloExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsModulo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerItemsModulo", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerItemsModuloResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsModuloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/LimpiarItemsRol", ReplyAction="http://tempuri.org/IServiceGestion/LimpiarItemsRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/LimpiarItemsRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void LimpiarItemsRol(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/LimpiarItemsRol", ReplyAction="http://tempuri.org/IServiceGestion/LimpiarItemsRolResponse")]
        System.Threading.Tasks.Task LimpiarItemsRolAsync(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarItemRol", ReplyAction="http://tempuri.org/IServiceGestion/AsignarItemRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/AsignarItemRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void AsignarItemRol(int idRol, int idItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarItemRol", ReplyAction="http://tempuri.org/IServiceGestion/AsignarItemRolResponse")]
        System.Threading.Tasks.Task AsignarItemRolAsync(int idRol, int idItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarPermisos", ReplyAction="http://tempuri.org/IServiceGestion/AsignarPermisosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/AsignarPermisosExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void AsignarPermisos(int usuarioRol, bool write, bool delete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarPermisos", ReplyAction="http://tempuri.org/IServiceGestion/AsignarPermisosResponse")]
        System.Threading.Tasks.Task AsignarPermisosAsync(int usuarioRol, bool write, bool delete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarPermisosTool", ReplyAction="http://tempuri.org/IServiceGestion/AsignarPermisosToolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/AsignarPermisosToolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void AsignarPermisosTool(int idUsuarioPermisos, int idTool, bool permitir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/AsignarPermisosTool", ReplyAction="http://tempuri.org/IServiceGestion/AsignarPermisosToolResponse")]
        System.Threading.Tasks.Task AsignarPermisosToolAsync(int idUsuarioPermisos, int idTool, bool permitir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerItemsRol", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerItemsRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerItemsRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsRol(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerItemsRol", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerItemsRolResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsRolAsync(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EliminarItemRol", ReplyAction="http://tempuri.org/IServiceGestion/EliminarItemRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EliminarItemRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EliminarItemRol(int idRol, int idItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EliminarItemRol", ReplyAction="http://tempuri.org/IServiceGestion/EliminarItemRolResponse")]
        System.Threading.Tasks.Task EliminarItemRolAsync(int idRol, int idItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarSistema", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarSistemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/RegistrarSistemaExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMSistema RegistrarSistema(string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarSistema", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarSistemaResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema> RegistrarSistemaAsync(string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarSistema", ReplyAction="http://tempuri.org/IServiceGestion/EditarSistemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EditarSistemaExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EditarSistema(int idSistema, string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarSistema", ReplyAction="http://tempuri.org/IServiceGestion/EditarSistemaResponse")]
        System.Threading.Tasks.Task EditarSistemaAsync(int idSistema, string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoSistemas", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoSistemasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoSistemasExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMSistema[] ObtenerCatalogoSistemas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoSistemas", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoSistemasResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema[]> ObtenerCatalogoSistemasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoSistemas", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoSistemasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerInfoSistemasExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMSistema ObtenerInfoSistemas(int idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoSistemas", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoSistemasResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema> ObtenerInfoSistemasAsync(int idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerModulosSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerModulosSistemaAppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerModulosSistemaAppExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMModulo[] ObtenerModulosSistemaApp(int idSistema, System.Nullable<bool> activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerModulosSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerModulosSistemaAppResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo[]> ObtenerModulosSistemaAppAsync(int idSistema, System.Nullable<bool> activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarModuloSistemaAppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/RegistrarModuloSistemaAppExceptionServiceFault" +
            "", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMModulo RegistrarModuloSistemaApp(string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarModuloSistemaAppResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo> RegistrarModuloSistemaAppAsync(string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/EditarModuloSistemaAppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EditarModuloSistemaAppExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EditarModuloSistemaApp(int idModulo, string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/EditarModuloSistemaAppResponse")]
        System.Threading.Tasks.Task EditarModuloSistemaAppAsync(int idModulo, string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoModuloSistemaAppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/ObtenerInfoModuloSistemaAppExceptionServiceFau" +
            "lt", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMModulo ObtenerInfoModuloSistemaApp(int idModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerInfoModuloSistemaApp", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerInfoModuloSistemaAppResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo> ObtenerInfoModuloSistemaAppAsync(int idModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarPaginaModulo", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarPaginaModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/RegistrarPaginaModuloExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMItemModulo RegistrarPaginaModulo(string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/RegistrarPaginaModulo", ReplyAction="http://tempuri.org/IServiceGestion/RegistrarPaginaModuloResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo> RegistrarPaginaModuloAsync(string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarPaginaModulo", ReplyAction="http://tempuri.org/IServiceGestion/EditarPaginaModuloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceGestion/EditarPaginaModuloExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void EditarPaginaModulo(int idPagina, string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/EditarPaginaModulo", ReplyAction="http://tempuri.org/IServiceGestion/EditarPaginaModuloResponse")]
        System.Threading.Tasks.Task EditarPaginaModuloAsync(int idPagina, string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoPaises", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoPaisesResponse")]
        Entidades.Serv_Admin.VMPais[] ObtenerCatalogoPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestion/ObtenerCatalogoPaises", ReplyAction="http://tempuri.org/IServiceGestion/ObtenerCatalogoPaisesResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMPais[]> ObtenerCatalogoPaisesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceGestionChannel : Entidades.Serv_Admin.IServiceGestion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGestionClient : System.ServiceModel.ClientBase<Entidades.Serv_Admin.IServiceGestion>, Entidades.Serv_Admin.IServiceGestion {
        
        public ServiceGestionClient() {
        }
        
        public ServiceGestionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGestionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGestionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGestionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.Serv_Admin.VMUsuario RegistrarNuevoUsuario(string nombre, string apellidoMaterno, string apellidoPaterno, string celular, string correo, string extension, int idEstatus, string password, string usuario_sistema) {
            return base.Channel.RegistrarNuevoUsuario(nombre, apellidoMaterno, apellidoPaterno, celular, correo, extension, idEstatus, password, usuario_sistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario> RegistrarNuevoUsuarioAsync(string nombre, string apellidoMaterno, string apellidoPaterno, string celular, string correo, string extension, int idEstatus, string password, string usuario_sistema) {
            return base.Channel.RegistrarNuevoUsuarioAsync(nombre, apellidoMaterno, apellidoPaterno, celular, correo, extension, idEstatus, password, usuario_sistema);
        }
        
        public void EditarUsuario(Entidades.Serv_Admin.VMUsuario usuario) {
            base.Channel.EditarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task EditarUsuarioAsync(Entidades.Serv_Admin.VMUsuario usuario) {
            return base.Channel.EditarUsuarioAsync(usuario);
        }
        
        public Entidades.Serv_Admin.VMUsuario[] ObtenerCatalogoUsuarios() {
            return base.Channel.ObtenerCatalogoUsuarios();
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario[]> ObtenerCatalogoUsuariosAsync() {
            return base.Channel.ObtenerCatalogoUsuariosAsync();
        }
        
        public void ResetPassUsuario(string usuario_sistema) {
            base.Channel.ResetPassUsuario(usuario_sistema);
        }
        
        public System.Threading.Tasks.Task ResetPassUsuarioAsync(string usuario_sistema) {
            return base.Channel.ResetPassUsuarioAsync(usuario_sistema);
        }
        
        public Entidades.Serv_Admin.VMUsuario ObtenerInfoUsuario(string usuario_sistema) {
            return base.Channel.ObtenerInfoUsuario(usuario_sistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMUsuario> ObtenerInfoUsuarioAsync(string usuario_sistema) {
            return base.Channel.ObtenerInfoUsuarioAsync(usuario_sistema);
        }
        
        public Entidades.Serv_Admin.VMRol[] ObtenerRoles(int idSistema) {
            return base.Channel.ObtenerRoles(idSistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesAsync(int idSistema) {
            return base.Channel.ObtenerRolesAsync(idSistema);
        }
        
        public Entidades.Serv_Admin.VMRol[] ObtenerRolesUsuario(string usuario, System.Nullable<int> idSistema) {
            return base.Channel.ObtenerRolesUsuario(usuario, idSistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesUsuarioAsync(string usuario, System.Nullable<int> idSistema) {
            return base.Channel.ObtenerRolesUsuarioAsync(usuario, idSistema);
        }
        
        public Entidades.Serv_Admin.VMRol RegistrarNuevoRol(string nombre, string descripcion, int idPais) {
            return base.Channel.RegistrarNuevoRol(nombre, descripcion, idPais);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol> RegistrarNuevoRolAsync(string nombre, string descripcion, int idPais) {
            return base.Channel.RegistrarNuevoRolAsync(nombre, descripcion, idPais);
        }
        
        public void AsignarRolUsuario(int idRol, string usuario) {
            base.Channel.AsignarRolUsuario(idRol, usuario);
        }
        
        public System.Threading.Tasks.Task AsignarRolUsuarioAsync(int idRol, string usuario) {
            return base.Channel.AsignarRolUsuarioAsync(idRol, usuario);
        }
        
        public void EliminarRolUsuario(int idRol, string usuario) {
            base.Channel.EliminarRolUsuario(idRol, usuario);
        }
        
        public System.Threading.Tasks.Task EliminarRolUsuarioAsync(int idRol, string usuario) {
            return base.Channel.EliminarRolUsuarioAsync(idRol, usuario);
        }
        
        public Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsModulo() {
            return base.Channel.ObtenerItemsModulo();
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsModuloAsync() {
            return base.Channel.ObtenerItemsModuloAsync();
        }
        
        public void LimpiarItemsRol(int idRol) {
            base.Channel.LimpiarItemsRol(idRol);
        }
        
        public System.Threading.Tasks.Task LimpiarItemsRolAsync(int idRol) {
            return base.Channel.LimpiarItemsRolAsync(idRol);
        }
        
        public void AsignarItemRol(int idRol, int idItem) {
            base.Channel.AsignarItemRol(idRol, idItem);
        }
        
        public System.Threading.Tasks.Task AsignarItemRolAsync(int idRol, int idItem) {
            return base.Channel.AsignarItemRolAsync(idRol, idItem);
        }
        
        public void AsignarPermisos(int usuarioRol, bool write, bool delete) {
            base.Channel.AsignarPermisos(usuarioRol, write, delete);
        }
        
        public System.Threading.Tasks.Task AsignarPermisosAsync(int usuarioRol, bool write, bool delete) {
            return base.Channel.AsignarPermisosAsync(usuarioRol, write, delete);
        }
        
        public void AsignarPermisosTool(int idUsuarioPermisos, int idTool, bool permitir) {
            base.Channel.AsignarPermisosTool(idUsuarioPermisos, idTool, permitir);
        }
        
        public System.Threading.Tasks.Task AsignarPermisosToolAsync(int idUsuarioPermisos, int idTool, bool permitir) {
            return base.Channel.AsignarPermisosToolAsync(idUsuarioPermisos, idTool, permitir);
        }
        
        public Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsRol(int idRol) {
            return base.Channel.ObtenerItemsRol(idRol);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsRolAsync(int idRol) {
            return base.Channel.ObtenerItemsRolAsync(idRol);
        }
        
        public void EliminarItemRol(int idRol, int idItem) {
            base.Channel.EliminarItemRol(idRol, idItem);
        }
        
        public System.Threading.Tasks.Task EliminarItemRolAsync(int idRol, int idItem) {
            return base.Channel.EliminarItemRolAsync(idRol, idItem);
        }
        
        public Entidades.Serv_Admin.VMSistema RegistrarSistema(string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo) {
            return base.Channel.RegistrarSistema(nombre, logo, urlhome, sistemaEmbebido, activo);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema> RegistrarSistemaAsync(string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo) {
            return base.Channel.RegistrarSistemaAsync(nombre, logo, urlhome, sistemaEmbebido, activo);
        }
        
        public void EditarSistema(int idSistema, string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo) {
            base.Channel.EditarSistema(idSistema, nombre, logo, urlhome, sistemaEmbebido, activo);
        }
        
        public System.Threading.Tasks.Task EditarSistemaAsync(int idSistema, string nombre, string logo, string urlhome, bool sistemaEmbebido, bool activo) {
            return base.Channel.EditarSistemaAsync(idSistema, nombre, logo, urlhome, sistemaEmbebido, activo);
        }
        
        public Entidades.Serv_Admin.VMSistema[] ObtenerCatalogoSistemas() {
            return base.Channel.ObtenerCatalogoSistemas();
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema[]> ObtenerCatalogoSistemasAsync() {
            return base.Channel.ObtenerCatalogoSistemasAsync();
        }
        
        public Entidades.Serv_Admin.VMSistema ObtenerInfoSistemas(int idSistema) {
            return base.Channel.ObtenerInfoSistemas(idSistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema> ObtenerInfoSistemasAsync(int idSistema) {
            return base.Channel.ObtenerInfoSistemasAsync(idSistema);
        }
        
        public Entidades.Serv_Admin.VMModulo[] ObtenerModulosSistemaApp(int idSistema, System.Nullable<bool> activo) {
            return base.Channel.ObtenerModulosSistemaApp(idSistema, activo);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo[]> ObtenerModulosSistemaAppAsync(int idSistema, System.Nullable<bool> activo) {
            return base.Channel.ObtenerModulosSistemaAppAsync(idSistema, activo);
        }
        
        public Entidades.Serv_Admin.VMModulo RegistrarModuloSistemaApp(string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo) {
            return base.Channel.RegistrarModuloSistemaApp(nombre, idSistema, urlIcono, urlDestino, dbConexion, activo);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo> RegistrarModuloSistemaAppAsync(string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo) {
            return base.Channel.RegistrarModuloSistemaAppAsync(nombre, idSistema, urlIcono, urlDestino, dbConexion, activo);
        }
        
        public void EditarModuloSistemaApp(int idModulo, string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo) {
            base.Channel.EditarModuloSistemaApp(idModulo, nombre, idSistema, urlIcono, urlDestino, dbConexion, activo);
        }
        
        public System.Threading.Tasks.Task EditarModuloSistemaAppAsync(int idModulo, string nombre, int idSistema, string urlIcono, string urlDestino, string dbConexion, bool activo) {
            return base.Channel.EditarModuloSistemaAppAsync(idModulo, nombre, idSistema, urlIcono, urlDestino, dbConexion, activo);
        }
        
        public Entidades.Serv_Admin.VMModulo ObtenerInfoModuloSistemaApp(int idModulo) {
            return base.Channel.ObtenerInfoModuloSistemaApp(idModulo);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMModulo> ObtenerInfoModuloSistemaAppAsync(int idModulo) {
            return base.Channel.ObtenerInfoModuloSistemaAppAsync(idModulo);
        }
        
        public Entidades.Serv_Admin.VMItemModulo RegistrarPaginaModulo(string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo) {
            return base.Channel.RegistrarPaginaModulo(nombre, idModulo, urlIcono, urlDestino, idItemPadre, orden, activo);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo> RegistrarPaginaModuloAsync(string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo) {
            return base.Channel.RegistrarPaginaModuloAsync(nombre, idModulo, urlIcono, urlDestino, idItemPadre, orden, activo);
        }
        
        public void EditarPaginaModulo(int idPagina, string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo) {
            base.Channel.EditarPaginaModulo(idPagina, nombre, idModulo, urlIcono, urlDestino, idItemPadre, orden, activo);
        }
        
        public System.Threading.Tasks.Task EditarPaginaModuloAsync(int idPagina, string nombre, int idModulo, string urlIcono, string urlDestino, int idItemPadre, int orden, bool activo) {
            return base.Channel.EditarPaginaModuloAsync(idPagina, nombre, idModulo, urlIcono, urlDestino, idItemPadre, orden, activo);
        }
        
        public Entidades.Serv_Admin.VMPais[] ObtenerCatalogoPaises() {
            return base.Channel.ObtenerCatalogoPaises();
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMPais[]> ObtenerCatalogoPaisesAsync() {
            return base.Channel.ObtenerCatalogoPaisesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serv_Admin.IServiceAcceso")]
    public interface IServiceAcceso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerItemsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerItemsUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerItemsUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerItemsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerItemsUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/IniciarSesion", ReplyAction="http://tempuri.org/IServiceAcceso/IniciarSesionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/IniciarSesionExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        string IniciarSesion(string usuario, string llave, string ip, string sistema, bool cerrarSesiones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/IniciarSesion", ReplyAction="http://tempuri.org/IServiceAcceso/IniciarSesionResponse")]
        System.Threading.Tasks.Task<string> IniciarSesionAsync(string usuario, string llave, string ip, string sistema, bool cerrarSesiones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/CerrarSesion", ReplyAction="http://tempuri.org/IServiceAcceso/CerrarSesionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/CerrarSesionExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void CerrarSesion(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/CerrarSesion", ReplyAction="http://tempuri.org/IServiceAcceso/CerrarSesionResponse")]
        System.Threading.Tasks.Task CerrarSesionAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerSistemasUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerSistemasUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerSistemasUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMSistema[] ObtenerSistemasUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerSistemasUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerSistemasUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema[]> ObtenerSistemasUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosItemsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerPermisosItemsUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosItemsUsuarioExceptionServiceFaul" +
            "t", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMPermisoItem[] ObtenerPermisosItemsUsuario(string usuario, System.Nullable<int> idSistema, System.Nullable<int> idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosItemsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerPermisosItemsUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMPermisoItem[]> ObtenerPermisosItemsUsuarioAsync(string usuario, System.Nullable<int> idSistema, System.Nullable<int> idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosToolsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerPermisosToolsUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosToolsUsuarioExceptionServiceFaul" +
            "t", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMToolItem[] ObtenerPermisosToolsUsuario(int idUsuarioPermisos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerPermisosToolsUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerPermisosToolsUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMToolItem[]> ObtenerPermisosToolsUsuarioAsync(int idUsuarioPermisos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerRolesDeUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerRolesDeUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerRolesDeUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMRol[] ObtenerRolesDeUsuario(string usuario, System.Nullable<int> idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerRolesDeUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerRolesDeUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesDeUsuarioAsync(string usuario, System.Nullable<int> idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerItemsDeRol", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerItemsDeRolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ObtenerItemsDeRolExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsDeRol(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ObtenerItemsDeRol", ReplyAction="http://tempuri.org/IServiceAcceso/ObtenerItemsDeRolResponse")]
        System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsDeRolAsync(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ModificarPasswordUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ModificarPasswordUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Entidades.Serv_Admin.ExceptionService), Action="http://tempuri.org/IServiceAcceso/ModificarPasswordUsuarioExceptionServiceFault", Name="ExceptionService", Namespace="http://schemas.datacontract.org/2004/07/ViewModel")]
        void ModificarPasswordUsuario(string idUsuario, string passAnterior, string passNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAcceso/ModificarPasswordUsuario", ReplyAction="http://tempuri.org/IServiceAcceso/ModificarPasswordUsuarioResponse")]
        System.Threading.Tasks.Task ModificarPasswordUsuarioAsync(string idUsuario, string passAnterior, string passNueva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAccesoChannel : Entidades.Serv_Admin.IServiceAcceso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAccesoClient : System.ServiceModel.ClientBase<Entidades.Serv_Admin.IServiceAcceso>, Entidades.Serv_Admin.IServiceAcceso {
        
        public ServiceAccesoClient() {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccesoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsUsuario(string usuario) {
            return base.Channel.ObtenerItemsUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsUsuarioAsync(string usuario) {
            return base.Channel.ObtenerItemsUsuarioAsync(usuario);
        }
        
        public string IniciarSesion(string usuario, string llave, string ip, string sistema, bool cerrarSesiones) {
            return base.Channel.IniciarSesion(usuario, llave, ip, sistema, cerrarSesiones);
        }
        
        public System.Threading.Tasks.Task<string> IniciarSesionAsync(string usuario, string llave, string ip, string sistema, bool cerrarSesiones) {
            return base.Channel.IniciarSesionAsync(usuario, llave, ip, sistema, cerrarSesiones);
        }
        
        public void CerrarSesion(string usuario) {
            base.Channel.CerrarSesion(usuario);
        }
        
        public System.Threading.Tasks.Task CerrarSesionAsync(string usuario) {
            return base.Channel.CerrarSesionAsync(usuario);
        }
        
        public Entidades.Serv_Admin.VMSistema[] ObtenerSistemasUsuario(string usuario) {
            return base.Channel.ObtenerSistemasUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMSistema[]> ObtenerSistemasUsuarioAsync(string usuario) {
            return base.Channel.ObtenerSistemasUsuarioAsync(usuario);
        }
        
        public Entidades.Serv_Admin.VMPermisoItem[] ObtenerPermisosItemsUsuario(string usuario, System.Nullable<int> idSistema, System.Nullable<int> idRol) {
            return base.Channel.ObtenerPermisosItemsUsuario(usuario, idSistema, idRol);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMPermisoItem[]> ObtenerPermisosItemsUsuarioAsync(string usuario, System.Nullable<int> idSistema, System.Nullable<int> idRol) {
            return base.Channel.ObtenerPermisosItemsUsuarioAsync(usuario, idSistema, idRol);
        }
        
        public Entidades.Serv_Admin.VMToolItem[] ObtenerPermisosToolsUsuario(int idUsuarioPermisos) {
            return base.Channel.ObtenerPermisosToolsUsuario(idUsuarioPermisos);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMToolItem[]> ObtenerPermisosToolsUsuarioAsync(int idUsuarioPermisos) {
            return base.Channel.ObtenerPermisosToolsUsuarioAsync(idUsuarioPermisos);
        }
        
        public Entidades.Serv_Admin.VMRol[] ObtenerRolesDeUsuario(string usuario, System.Nullable<int> idSistema) {
            return base.Channel.ObtenerRolesDeUsuario(usuario, idSistema);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMRol[]> ObtenerRolesDeUsuarioAsync(string usuario, System.Nullable<int> idSistema) {
            return base.Channel.ObtenerRolesDeUsuarioAsync(usuario, idSistema);
        }
        
        public Entidades.Serv_Admin.VMItemModulo[] ObtenerItemsDeRol(int idRol) {
            return base.Channel.ObtenerItemsDeRol(idRol);
        }
        
        public System.Threading.Tasks.Task<Entidades.Serv_Admin.VMItemModulo[]> ObtenerItemsDeRolAsync(int idRol) {
            return base.Channel.ObtenerItemsDeRolAsync(idRol);
        }
        
        public void ModificarPasswordUsuario(string idUsuario, string passAnterior, string passNueva) {
            base.Channel.ModificarPasswordUsuario(idUsuario, passAnterior, passNueva);
        }
        
        public System.Threading.Tasks.Task ModificarPasswordUsuarioAsync(string idUsuario, string passAnterior, string passNueva) {
            return base.Channel.ModificarPasswordUsuarioAsync(idUsuario, passAnterior, passNueva);
        }
    }
}
